[book]
authors = ["Danny Ben Shitrit"]
language = "en"
multilingual = false
src = "src"
title = "Runfile Documentation"

[build]
build-dir = "docs"
create-missing = false

[output.html]
git-repository-url = "https://github.com/dannyben/runfile"


[output.html.fold]
enable = true
