serve: foreman start
#? serve with foreman

build: mdbook build
#? build with mdbook

test: test/test.sh
#? run tests

spell: test/spell_check.sh
#? run spellcheck tests

sla: test/broken_links.sh
#? run site link analyzer

livereload: test/live_reload.sh
#? run live_reload tests

